### ISSUE TITLE
Allow NoahMP to export albedo

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#2616]
**Description:**
At this point, NoahMP land component does not export albedo components to FV3. Albedo update is controlled by `IALB` (or `iamb` in `input.nml`) option and FV3 gets those from land component when it set to 2 (default when NoahMP is used by CCPP)

As a reference: https://github.com/ufs-community/ccpp-physics/blob/dce8be6515a5bdac7f281d0c8c2bdbc227592a6f/physics/Radiation/radiation_surface.f#L588

**Possible fix:**
- Add extra albedo variables to the NoahMP export state
- Update CMEPS to allow exchanging new land related variables
- Add new variables to CCPP sfc_land to complete the loop
- This will potentially change answer for land component related RTs

**Comment by uturuncoglu** [comment]
FYI, @barlage @JustinPerket @DeniseWorthen

**Comment by gspetro-NOAA** [comment]
@uturuncoglu Is work planned for this issue?

**Comment by uturuncoglu** [comment]
@gspetro-NOAA No, the project is ended but I think this needs to be done for fully coupled configuration ant it is straightforward to implement. @barlage if you guide me (such as which variables needs to be connected - noahmp vs. Ccpp side) I could try to close the loop in my free time. Let me know what you think?

**Comment by JustinPerket** [comment]
I have recently reviewed this area for my in-progress coupled Atmosphere-LM4 branches. I don't currently have separate clean branches to share, and don't touch the Noah-MP side of things, but I link these fields in `fd_ufs.yaml`:

```yaml
    - standard_name: Sl_anidf
      alias: inst_lnd_ir_dif_albedo
      canonical_units: 1
      description: land export
    #
    - standard_name: Sl_anidr
      alias: inst_lnd_ir_dir_albedo
      canonical_units: 1
      description: land export
    #
    - standard_name: Sl_avsdf
      alias: inst_lnd_vis_dif_albedo
      canonical_units: 1
      description: land export
    #
    - standard_name: Sl_avsdr
      alias: inst_lnd_vis_dir_albedo
      canonical_units: 1
      description: land export
```

to what what will be used in rrtmg. Respectively in FV3:

```Fortran
GFS_Sfcprop%albdifnir_lnd
GFS_Sfcprop%albdirnir_lnd
GFS_Sfcprop%albdifvis_lnd
GFS_Sfcprop%albdirvis_lnd
```

Like @uturuncoglu said, it's pretty straightforward code-wise, but I can assist more if you want. I also have something similar for land radiative temperature connecting from LM4 component to the atmosphere's rrtmg lw.
